collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-redirect-from

postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]

url: "https://pfbeautysalon.github.io/"
baseurl: ""